events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # Настройки логирования запросов Nginx
    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';

    access_log /var/log/nginx/access.log main;

    # Выделяем 10 МБ под зону лимитов по IP. Разрешаем 3 запроса в секунду (как в Go-коде)
    limit_req_zone $binary_remote_addr zone=login_limit:10m rate=3r/s;

    server {
        # Слушаем обычный HTTP (80) и защищенный HTTPS (443)
        listen 80;
        listen 443 ssl;
        server_name localhost;

        # Пути к сертификатам внутри контейнера
        ssl_certificate /etc/nginx/ssl/server.crt;
        ssl_certificate_key /etc/nginx/ssl/server.key;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;

        # Проксирование API запросов и видеотрансляции
        location /api/ {
            limit_req zone=login_limit burst=5 nodelay; # burst=5 как в Go-коде

            proxy_pass http://app:8080;
            proxy_http_version 1.1;

            # КРИТИЧЕСКИ ВАЖНО ДЛЯ MJPEG: отключаем буферизацию и кэш Nginx,
            # чтобы видео шло в реальном времени без задержек и накопления в ОЗУ
            proxy_buffering off;
            proxy_cache off;
            chunked_transfer_encoding on;

            # === ДОБАВЛЕННОЕ ИСПРАВЛЕНИЕ: Защита от обрыва стрима ===
            # Увеличиваем время ожидания до 24 часов, чтобы Nginx не рвал бесконечный видеопоток
            proxy_read_timeout 86400s;
            proxy_send_timeout 86400s;

            # Фиксируем Host и Real-IP
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;

            # Вместо $proxy_add_x_forwarded_for пишем строго $remote_addr.
            # Это сотрет любые фейковые IP, которые хакер пытался передать.
            proxy_set_header X-Forwarded-For $remote_addr;
        }

        # Раздача фронтенда
        location / {
            proxy_pass http://app:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_buffering off;
            proxy_cache off;
            chunked_transfer_encoding on;
        }
    }
}
